### ISSUE TITLE
Thailand APK Sync Failing at 100% Sync

### ISSUE THREAD

**Issue by samkanga** [OpenSRP/opensrp-client-reveal#1033] opened 2020-09-19 12:20 UTC
- [x] On version 5.2.10 of the Thailand APK,
- Added a structure and completed a HH registration. 
- Hit the sync button
- It progresses through the 100% mark showing the different items being synced 
- The syncing toast, then changes to sync failed (See screenshot below)  and then the "Device data not synced" message comes up in the hamburger menu

![image](https://user-images.githubusercontent.com/5908630/93667051-9414a300-fa8b-11ea-9792-8ff057b9f8cf.png)

**Comment by githengi** [comment] 2020-09-19 16:05
This was being caused by errors on the API.

This was because of events tagging keys for checkboxes while the server did not have the updated interface for Obs.

Deserialization was failing causing this error.

Updating OpenSRP with latest version resolved the issue.

@samkanga close the issue after confirming this

**Comment by samkanga** [comment] 2020-09-22 07:49
I confirm this is now working.

**Closed** 2020-09-22 07:49 UTC
Labels: Priority: High
