### ISSUE TITLE
Larval and Mosquito Card Views don't request for Supervisor password if disabled

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#295] opened 2019-07-09 09:49 UTC
- [ ] Larval and Mosquito Card Views don't request for Supervisor password if disabled.

- [ ] Currently when requesting for Supervisor password when far from structures is disabled the password is still requested when trying to launch form from card views

**Comment by craigappl** [comment] 2019-07-16 14:06
Closing because it's a duplicate of #304

**Closed by craigappl** 2019-07-16 14:06 UTC
Labels: Size: Small (≤1), bug
