### ISSUE TITLE
Register Family Tasks don't appear to be closing on Android

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#211] opened 2019-06-03 22:35 UTC
- The register family task is not properly registering the family and closing the register family task
- The generate task for bednet distribution is functioning
- The blood screening task for the head of household was showing up
- Users could to through and register other family members completely. When they navigate out

CHECK THIS OTHER POSSIBILITY 
Are there multiple register family tasks assigned to a single location?

**Comment by githengi** [comment] 2019-06-10 12:01
Not able to reproduce on current master or version 2.0.5

**Comment by githengi** [comment] 2019-06-10 12:01
Was a known issue for version 2.0.4 but was resolved in version 2.0.5

**Comment by githengi** [comment] 2019-06-11 11:54
Researched on the `Riley` family which has a family registered twice on the same structure, the issue caused by version 2.0.0 of the APK a family was created on 14th May but the task was never closed. Christina was able to registers a family again on version 2.0.5 on June 10th. This time the task was closed and its not possible to register family on that structure again

**Closed** 2019-06-11 11:55 UTC
Labels: bug
